backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

#publish_mode: editorial_workflow #optional, enables publishing workflow

collections:
  #yaml middleman data example
  - name: pages
    label: Pages
    files:
      - file: "data/pages/home.yml"
        label: Homepage
        name: home
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - { label: Title, name: title, widget: string }
              - { label: Image, name: image, widget: image }
          - label: Story
            name: story
            widget: markdown
          - label: Logo
            name: logo
            widget: image
          - label: "Website coming soon"
            name: website_coming_soon
            widget: image

  - name: settings
    label: Settings
    files:
      - file: data/settings/navigation.yml
        label: Navigation
        name: navigation
        fields:
          - label: Navigation
            name: nav_items
            widget: list
            fields:
              - { label: Label, name: label, widget: string }
              - { label: Path, name: path, widget: string }
